# Generated by Django 2.0.4 on 2018-05-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'N/A'), (1, 'President'), (2, 'Vice-President'), (3, 'Secretary'), (4, 'Assistant-Secretary'), (5, 'Treasurer'), (6, 'Assistant-Treasurer'), (7, 'PRO')], default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position'),
        ),
    ]
