# Generated by Django 2.0.4 on 2018-05-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20180502_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='party',
        ),
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.Party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'President'), (2, 'Vice-President'), (3, 'Secretary'), (4, 'Assistant-Secretary'), (5, 'Treasurer'), (6, 'Assistant-Treasurer'), (7, 'PRO')], default=0),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
