# Generated by Django 2.0.4 on 2018-05-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20180504_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='party',
        ),
    ]
