# Generated by Django 2.0.4 on 2018-05-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20180504_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
