# Generated by Django 2.0.4 on 2018-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_vote_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
